service: xcerpt-telegram-bot

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  environment:
    API_TOKEN: 
    LOGGING_LEVEL: debug
  stage: dev
  region: ap-south-1
  vpc:
    securityGroupIds:
      - sg-0dfb6943ccb4edd3d
    subnetIds:
      - subnet-00f2XXXXXX1cce08a
      - subnet-0270XXXXXX07a7113
      - subnet-0e80XXXXXXXX036c8
  iamRoleStatements:
    - Effect: Allow
      Action: "rds-db:connect"
      Resource: "arn:aws:rds-db:ap-south-1:6XXXXXXXX8:dbuser:prx-0XXXXXXXXXXXXXXX*"

package:
  exclude:
    - ./**
  include:
    - src/**

plugins:
  - serverless-python-requirements

functions:
  index-function:
    handler: src/lambda_function.lambda_handler
    layers:
      - arn:aws:lambda:ap-south-1:77XXXXXXXXX8:layer:Klayers-python38-pandas:32
      - arn:aws:lambda:ap-south-1:77XXXXXXXXX8:layer:Klayers-python38-aws-psycopg2:1
      - arn:aws:lambda:ap-south-1:77XXXXXXXXX8:layer:Klayers-python38-Pillow:10
    events:
      - schedule:
          rate: rate(1 hour)
          enabled: true
          input:
            message: ${file(./src/Data/consensus_config.json)}
